name       : python-docutils
version    : '0.19'
release    : 11
source     :
    - https://files.pythonhosted.org/packages/source/d/docutils/docutils-0.19.tar.gz : 33995a6753c30b7f577febfc2c50411fec6aac7f7ffeb7c4cfe5991072dcf9e6
homepage   : https://docutils.sourceforge.io/
license    :
    - CC0-1.0
    - BSD-2-Clause
    - GPL-3.0-or-later
    - Python-2.0
component  : programming.python
summary    : Python Documentation Utilities
description: |
    Docutils is a modular system for processing documentation into useful formats, such as HTML, XML, and LaTeX. For input Docutils supports reStructuredText, an easy-to-read, what-you-see-is-what-you-get plaintext markup syntax.
builddeps  :
    - python-recommonmark # check
build      : |
    %python3_setup
install    : |
    %python3_install
    # Remove .py extension
    for _f in "$installdir"/usr/bin/*.py; do
      mv -v "$_f" "${_f%.py}"
    done
check      : |
    %python3_test test/alltests.py
