name        : python-docutils
version     : 0.13.1
release     : 3
source      :
    - https://pypi.python.org/packages/05/25/7b5484aca5d46915493f1fd4ecb63c38c333bd32aa9ad6e19da8d08895ae/docutils-0.13.1.tar.gz : 718c0f5fb677be0f34b781e04241c4067cbd9327b66bdd8e763201130f5175be
homepage    : https://pypi.python.org/pypi/docutils
license     : Public Domain
component   : programming.python
summary     : Python Documentation Utilities
description : |
    Docutils is a modular system for processing documentation into useful formats, such as HTML, XML, and LaTeX. For input Docutils supports reStructuredText, an easy-to-read, what-you-see-is-what-you-get plaintext markup syntax.
builddeps  :
    - pkgconfig(python-3.5)
    - python-setuptools
build      : |
    %python_setup
    %python3_setup
install    : |
    %python3_install
    # fix python 2/3 conflict
    for _f in "$installdir"/usr/bin/*.py; do
      mv -v "$_f" "${_f%.py}-py3.py"
    done
    %python_install
    

    

     
