name       : python-docutils
version    : 0.15.2
release    : 6
source     :
    - https://files.pythonhosted.org/packages/93/22/953e071b589b0b1fee420ab06a0d15e5aa0c7470eb9966d60393ce58ad61/docutils-0.15.2.tar.gz : a2aeea129088da402665e92e0b25b04b073c04b2dce4ab65caaa38b7ce2e1a99
license    :
    - CC0-1.0
    - BSD-2-Clause
    - GPL-3.0
    - Python-2.0
component  : programming.python
summary    : Python Documentation Utilities
description: |
    Docutils is a modular system for processing documentation into useful formats, such as HTML, XML, and LaTeX. For input Docutils supports reStructuredText, an easy-to-read, what-you-see-is-what-you-get plaintext markup syntax.
builddeps  :
    - pkgconfig(python3)
    - python-setuptools
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    # Remove .py extension
    for _f in "$installdir"/usr/bin/*.py; do
      mv -v "$_f" "${_f%.py}"
    done
    %python3_install
    # Remove .py extension and append -3
    for _f in "$installdir"/usr/bin/*.py; do
      mv -v "$_f" "${_f%.py}-3"
    done
