name       : python-docutils
version    : '0.16'
release    : 7
source     :
    - https://files.pythonhosted.org/packages/2f/e0/3d435b34abd2d62e8206171892f174b180cd37b09d57b924ca5c2ef2219d/docutils-0.16.tar.gz : c2de3a60e9e7d07be26b7f2b00ca0309c207e06c100f9cc2a94931fc75a478fc
homepage   : https://docutils.sourceforge.io/
license    :
    - CC0-1.0
    - BSD-2-Clause
    - GPL-3.0-or-later
    - Python-2.0
component  : programming.python
summary    : Python Documentation Utilities
description: |
    Docutils is a modular system for processing documentation into useful formats, such as HTML, XML, and LaTeX. For input Docutils supports reStructuredText, an easy-to-read, what-you-see-is-what-you-get plaintext markup syntax.
builddeps  :
    - pkgconfig(python3)
    - python-setuptools
    - pygments
rundeps    :
    - pygments
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    # Remove .py extension
    for _f in "$installdir"/usr/bin/*.py; do
      mv -v "$_f" "${_f%.py}"
    done
    %python3_install
    # Remove .py extension and append -3
    for _f in "$installdir"/usr/bin/*.py; do
      mv -v "$_f" "${_f%.py}-3"
    done
check      : |
    %python_test
    %python3_test
