name       : python-docutils
version    : 0.14
release    : 3
source     :
    - https://pypi.python.org/packages/84/f4/5771e41fdf52aabebbadecc9381d11dea0fa34e4759b4071244fa094804c/docutils-0.14.tar.gz : 51e64ef2ebfb29cae1faa133b3710143496eca21c530f3f71424d77687764274
license    :
     - CC0-1.0
     - BSD-2-Clause
     - GPL-3.0
     - Python-2.0
component  : programming.python
summary    : Python Documentation Utilities
description: |
    Docutils is a modular system for processing documentation into useful formats, such as HTML, XML, and LaTeX. For input Docutils supports reStructuredText, an easy-to-read, what-you-see-is-what-you-get plaintext markup syntax.
builddeps  :
    - pkgconfig(python3)
    - python-setuptools
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    # Remove .py extension
    for _f in "$installdir"/usr/bin/*.py; do
      mv -v "$_f" "${_f%.py}"
    done
    %python3_install
    # Remove .py extension and append -3
    for _f in "$installdir"/usr/bin/*.py; do
      mv -v "$_f" "${_f%.py}-3"
    done
